services:
#    mathilde_duval.example:
#        class: MathildeDuvalBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    ens.jobeet.admin.category:
        class: MathildeDuvalBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, MathildeDuvalBundle\Entity\Category, MathildeDuvalBundle:CategoryAdmin]

    ens.jobeet.admin.job:
        class: MathildeDuvalBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null, MathildeDuvalBundle\Entity\Job, MathildeDuvalBundle:JobAdmin]
